### ISSUE TITLE
/pages/about/index

### ISSUE THREAD

**Issue by HeskeyBaozi** [HeskeyBaozi/blog-prod-comments#6]
https://heskeybaozi.github.io/#/pages/about/index

**Comment by HeskeyBaozi** [comment]
吼吼！现在已经支持评论功能了！用`Github issues`功能就可以实现评论！
在`主题配置文件`，也就是`lite/__config.yml`里编辑下面的字段。
```yaml
# https://github.com/imsun/gitment#customize
gitment:
  enable: true # 这里设置为true
  github_id: HeskeyBaozi # 你的Github名字
  repository_name: blog-prod-comments # 用来存放issues的仓库名字
  client_id: 005ba9093b6e776749ae # Github提供的OAuth信息
  client_secret: 2414f55a575d7986bfda2686d6f32a0551d2957e
  per_page: 8 # 评论分页
  max_comment_height: 250 # 250px # 最大评论高度
```
